### ISSUE TITLE
【需求】希望新增路由卡片菜单，方便切换，如图

### ISSUE THREAD

**Issue by chownchen** [hiui-group/classic-theme#49]
![image](https://user-images.githubusercontent.com/18654951/112089885-74db0780-8bcd-11eb-93c5-f58210c3c57f.png)

**Comment by chownchen** [comment]
来自彭亚军

**Comment by wugaoliang1116** [comment]
同时实现react-keep-alive功能

**Comment by wugaoliang1116** [comment]
![image](https://user-images.githubusercontent.com/24740506/122703278-c7d36200-d283-11eb-8b85-fda63a9b2f17.png)
