### ISSUE TITLE
路由配置中增加withoutLayout属性后会导致组件重新mount

### ISSUE THREAD

**Issue by wyyufeng** [hiui-group/classic-theme#74]
https://github.com/hiui-group/classic-theme/blob/master/src/components/Layout/GenuineLayout.jsx#L45
```javascript
const isWithoutLayout = currentMenu && currentMenu.withoutLayout
```
此处`isWithoutLayout`初始为null，如果配置里有`withoutLayout:true` ，会导致render里的条件发生变化,组件会重新mount,相应的生命周期也会执行两次

**Comment by Flcwl** [comment]
@wyyufeng classic-theme 3.5.2 DONE.
